### PR TITLE
what is going on here...

### PR DESCRIPTION
**Pull request by strohlaj**

### CODE REVIEW

**Comment by strohlaj** [comment]
Not sure why but it's not letting me merge this. it keeps moving this pull request over to the butchersboy  pull request. Still figuring out github. :(

**Comment by ButchersBoy** [comment]
dunno mate, I merged your changes in a while back... happy new year!

**Comment by strohlaj** [comment]
Happy new year!

I'm really new to git/github so I'm just wrestling with how to pull in your latest changes. Please excuse this nonsense!

**Comment by SuicSoft** [comment]
I recommend you use the git shell or GitHub for WIndows for pulling commits. This has happened to me once.. You need to contact the github support and then they'll delete it (maybe GitHub should add an option to delete a PR if it is newer then 1 hour) .

**Comment by punker76** [comment]
@SuicSoft Closing a PR is already implemented!

image

**Comment by SuicSoft** [comment]
@punker76 Not closing , but deleting the pull request

**Comment by punker76** [comment]
@SuicSoft ...close and forget...

**Comment by oniony** [comment]
Wasn't this closed in January?

**Pull request closed without merging**
