### PR TITLE
ported Dragablz to .Net Core 3.0

### PR DESCRIPTION
**Pull request by Mrxx99**
This changed the old projects to the new project SDK which allows multitargeting.
It still targets .Net Framework 4.0 and 4.5 but now additional .Net Core 3.0.
I changed the mocking framework in the test project to FakeItEasy because it allows to be used from .Net 4.0 to .Net Core 3.0.

EDIT: I also deleted the nuspec file, since in the new project sdk this info can be added directly in the project (I copied the infos). That's why the CI build was failing.

### CODE REVIEW

**Comment by ButchersBoy** [comment]
Hi, I'll try and have a look at appveyor to get the build working

**Comment by jeremyVignelles** [comment]
@ButchersBoy ; Hey, good to see you back 🙂 Hope you're doing well.
I'm really looking forward any progress with this library 👍 
Feel free to come and chat on gitter if you need help from the community to handle the issues.

**Comment by Mrxx99** [comment]
Great to see some activity here again :)

I think one point that failed the build was the deletion of nuspec file because I moved the infos of it into the csproj like suggested by microsoft which allows generating nuget package on build. I will try adding the nuspec again and see if build than succeeds

**Comment by jeremyVignelles** [comment]
nuspec shouldn't be needed if the CI is properly configured, right?

I would expect the nuspec file to be only used where there is no proj file

**Comment by akanieski** [comment]
I could use this nuget on a 3.1 project I'm working on as well.

**Comment by csutcliff** [comment]
For anyone wanting a solution in the meantime @miroiu has a .net core 3.1 fork that's available on NuGet https://github.com/miroiu/Dragablz https://www.nuget.org/packages/Dragablz.NetCore/0.3.3

**Comment by miroiu** [comment]
Hi! Thanks for upgrading this to .NET Core. I removed my listing from nuget.

**Pull request merged**
